<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php'; require_once __DIR__.'/includes/functions.php'; require_once __DIR__.'/includes/csrf.php';
$u=require_login(); $id=(int)($_GET['id']??$_POST['id']??0); $pdo=db(); $s=$pdo->prepare("SELECT * FROM listings WHERE id=? AND user_id=? AND status<>'removed' LIMIT 1"); $s->execute([$id,$u['id']]); $l=$s->fetch(); if(!$l){http_response_code(403);exit('Listing not available.');} if(($l['availability_status']??'available')==='sold'){http_response_code(409);exit('Sold listings cannot be edited.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  verify_csrf(); $title=trim((string)($_POST['title']??'')); $description=trim((string)($_POST['description']??'')); $category=strtolower(trim((string)($_POST['category']??''))); $brand=trim((string)($_POST['brand']??'')); $condition=strtolower(trim((string)($_POST['condition']??''))); $priceRaw=trim((string)($_POST['price']??'')); $location=trim((string)($_POST['location']??'')); $latRaw=trim((string)($_POST['latitude']??'')); $lngRaw=trim((string)($_POST['longitude']??''));
  if(mb_strlen($title)<3||mb_strlen($title)>180||mb_strlen($description)<10||$category===''||mb_strlen($category)>80||mb_strlen($brand)>100) throw new RuntimeException('Complete all required listing fields with valid lengths.');
  if(!in_array($condition,['new','excellent','good','fair','poor'],true)) throw new RuntimeException('Invalid item condition.');
  if($priceRaw===''||!is_numeric($priceRaw)) throw new RuntimeException('Enter a valid price.'); $price=(float)$priceRaw; if(!is_finite($price)||$price<=0||$price>100000000) throw new RuntimeException('Enter a valid price.');
  if($location===''||mb_strlen($location)>190) throw new RuntimeException('Enter a valid location.');
  $lat=null;if($latRaw!==''){if(!is_numeric($latRaw))throw new RuntimeException('Invalid latitude.');$lat=(float)$latRaw;if(!is_finite($lat)||$lat<-90||$lat>90)throw new RuntimeException('Latitude must be between -90 and 90.');}
  $lng=null;if($lngRaw!==''){if(!is_numeric($lngRaw))throw new RuntimeException('Invalid longitude.');$lng=(float)$lngRaw;if(!is_finite($lng)||$lng<-180||$lng>180)throw new RuntimeException('Longitude must be between -180 and 180.');}
  $q=$pdo->prepare("UPDATE listings SET title=?,description=?,category=?,brand=?,item_condition=?,price=?,location=?,latitude=?,longitude=?,status='pending',availability_status='available',fraud_score=NULL,trust_status=NULL,fraud_checked=0,updated_at=NOW() WHERE id=? AND user_id=?");
  $q->execute([$title,$description,$category,$brand,$condition,$price,$location,$lat,$lng,$id,$u['id']]);
  $result=null;try{$result=run_fraud_analysis($id);}catch(Throwable $aiError){error_log('Re-analysis failed for listing '.$id.': '.$aiError->getMessage());}
  flash($result?'success':'error',$result?'Listing updated and re-analyzed.':'Listing updated, but analysis is unavailable. The old score was cleared and the listing remains private pending review.'); redirect('/listing.php?id='.$id);
 }catch(RuntimeException $e){flash('error',$e->getMessage());redirect('/edit-listing.php?id='.$id);}
}
$pageTitle='Edit Listing'; include __DIR__.'/includes/header.php';?>
<form class="form-card" method="post"><h1>Edit listing</h1><p class="muted">Changing listing details clears the previous risk result and sends the updated content through analysis again.</p><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><div class="form-grid"><div class="field full"><label>Title</label><input name="title" maxlength="180" value="<?=e($l['title'])?>" required></div><div class="field full"><label>Description</label><textarea name="description" required><?=e($l['description'])?></textarea></div><div class="field"><label>Category</label><input name="category" maxlength="80" value="<?=e($l['category'])?>" required></div><div class="field"><label>Brand</label><input name="brand" maxlength="100" value="<?=e((string)$l['brand'])?>"></div><div class="field"><label>Condition</label><select name="condition"><?php foreach(['new','excellent','good','fair','poor'] as $v):?><option value="<?=$v?>" <?=$l['item_condition']===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></div><div class="field"><label>Price</label><input type="number" name="price" value="<?=e((string)$l['price'])?>" min="1" max="100000000" step="0.01" required></div><div class="field full"><label>Location</label><input name="location" maxlength="190" value="<?=e($l['location'])?>" required></div><div class="field"><label>Latitude</label><input name="latitude" inputmode="decimal" value="<?=e((string)$l['latitude'])?>"></div><div class="field"><label>Longitude</label><input name="longitude" inputmode="decimal" value="<?=e((string)$l['longitude'])?>"></div></div><div class="actions"><button type="button" class="btn btn-light" data-use-location>Use my location</button><button class="btn">Save & Re-analyze</button></div></form><?php include __DIR__.'/includes/footer.php';?>
