<?php
require_once __DIR__.'/includes/functions.php';
$pdo=db();
$recent=$pdo->query("SELECT l.*,u.name seller_name,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path FROM listings l JOIN users u ON u.id=l.user_id WHERE l.status='approved' ORDER BY l.created_at DESC LIMIT 8")->fetchAll();
$cats=$pdo->query("SELECT category,COUNT(*) total FROM listings WHERE status='approved' GROUP BY category ORDER BY total DESC LIMIT 6")->fetchAll();
$pageTitle='Buy & Sell Near You'; include __DIR__.'/includes/header.php';?>
<section class="hero"><div><div class="eyebrow">Nearby. Trusted. Secondhand.</div><h1>Buy & Sell Near You — With More Trust</h1><p>Find great secondhand products nearby with RADIUS's explainable AI-powered trust system.</p><div class="hero-actions"><a class="btn" href="/listings.php">Browse Listings</a><a class="btn btn-light" href="/create-listing.php">Sell an Item</a></div></div><div class="trust-card"><div class="section-head" style="margin-top:0"><div><h2>Trust Radar</h2><p>See nearby listings through a risk-aware lens.</p></div></div><div class="radar"><span class="node good"></span><span class="node warn"></span><span class="node sus"></span></div></div></section>
<div class="section-head"><div><h2>Explore categories</h2><p>Popular secondhand categories around you.</p></div></div><div class="grid"><?php foreach($cats as $c):?><a class="card card-body" href="/listings.php?category=<?=urlencode($c['category'])?>"><strong><?=e(ucfirst($c['category']))?></strong><span class="muted"><?=e((string)$c['total'])?> listings</span></a><?php endforeach;?></div>
<div class="section-head"><div><h2>Recently added</h2><p>Fresh listings that passed or cleared moderation.</p></div><a href="/listings.php">View all →</a></div><div class="grid"><?php foreach($recent as $l):?><a class="card" href="/listing.php?id=<?=$l['id']?>"><?php if($l['image_path']):?><img class="product-img" src="<?=e($l['image_path'])?>" alt=""><?php else:?><div class="product-img placeholder">RADIUS</div><?php endif;?><div class="card-body"><span class="badge <?=e(trust_class($l['trust_status'] ?? ''))?>"><?=e(trust_label($l['trust_status'] ?? ''))?></span><h3><?=e($l['title'])?></h3><div class="price"><?=money($l['price'])?></div><div class="meta"><span><?=e($l['item_condition'])?></span><span><?=e($l['location'])?></span><span><?=e($l['seller_name'])?></span></div></div></a><?php endforeach;?></div>
<div class="section-head"><div><h2>How RADIUS protects users</h2><p>Signals stay explainable and admins keep the final decision.</p></div></div><div class="grid"><div class="card card-body"><strong>Image reuse signal</strong><p class="muted">Perceptual hashes flag highly similar uploaded photos without claiming theft as fact.</p></div><div class="card card-body"><strong>Price anomaly</strong><p class="muted">A Random Forest estimates a market range and identifies unusually low prices.</p></div><div class="card card-body"><strong>Text + policy risk</strong><p class="muted">TF-IDF/Naive Bayes and policy rules highlight urgency or off-platform behavior.</p></div><div class="card card-body"><strong>Human moderation</strong><p class="muted">Suspicious and high-risk listings go to an admin queue for approval/removal.</p></div></div>
<?php include __DIR__.'/includes/footer.php';?>