<?php
require_once __DIR__.'/includes/functions.php';
$q=trim($_GET['q']??'');$cat=trim($_GET['category']??'');$cond=trim($_GET['condition']??'');$trust=trim($_GET['trust']??'');$min=$_GET['min_price']??'';$max=$_GET['max_price']??'';$radius=$_GET['radius']??'';$lat=$_GET['lat']??'';$lng=$_GET['lng']??'';$sort=$_GET['sort']??'newest';
$where=["l.status='approved'"];$params=[];
if($q!==''){$where[]='(l.title LIKE :q1 OR l.description LIKE :q2 OR l.brand LIKE :q3)';$params[':q1']='%'.$q.'%';$params[':q2']='%'.$q.'%';$params[':q3']='%'.$q.'%';}
if($cat!==''){$where[]='l.category=:cat';$params[':cat']=$cat;}if($cond!==''){$where[]='l.item_condition=:cond';$params[':cond']=$cond;}if($trust!==''){$where[]='l.trust_status=:trust';$params[':trust']=$trust;}if($min!==''){$where[]='l.price>=:min';$params[':min']=(float)$min;}if($max!==''){$where[]='l.price<=:max';$params[':max']=(float)$max;}
$distance='NULL';$having='';if($lat!==''&&$lng!==''&&$radius!==''){$distance=haversine_sql();$params[':ulat1']=(float)$lat;$params[':ulat2']=(float)$lat;$params[':ulng']=(float)$lng;$having=' HAVING distance_km <= :radius';$params[':radius']=(float)$radius;}
$order=match($sort){'price_asc'=>'l.price ASC','price_desc'=>'l.price DESC','distance'=>($distance==='NULL'?'l.created_at DESC':'distance_km ASC'),'newest'=>'l.created_at DESC',default=>'l.created_at DESC'};
$sql="SELECT l.*,u.name seller_name,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path,$distance distance_km FROM listings l JOIN users u ON u.id=l.user_id WHERE ".implode(' AND ',$where).$having." ORDER BY $order LIMIT 100";$s=db()->prepare($sql);$s->execute($params);$items=$s->fetchAll();
$pageTitle='Marketplace';include __DIR__.'/includes/header.php';?><div class="section-head"><div><h2>Marketplace</h2><p>Search, filter, and discover nearby secondhand products.</p></div></div><form class="filters"><input name="q" value="<?=e($q)?>" placeholder="Search products"><input name="category" value="<?=e($cat)?>" placeholder="Category"><select name="condition"><option value="">Condition</option><?php foreach(['new','excellent','good','fair','poor'] as $v):?><option <?=$cond===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select><input type="number" name="min_price" value="<?=e((string)$min)?>" placeholder="Min ৳"><input type="number" name="max_price" value="<?=e((string)$max)?>" placeholder="Max ৳"><select name="trust"><option value="">Trust</option><?php foreach(['safe','low_risk','suspicious','high_risk'] as $v):?><option value="<?=$v?>" <?=$trust===$v?'selected':''?>><?=trust_label($v)?></option><?php endforeach;?></select><select name="sort"><option value="newest">Newest</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Price ↑</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Price ↓</option><option value="distance" <?=$sort==='distance'?'selected':''?>>Distance</option></select><input name="lat" value="<?=e((string)$lat)?>" placeholder="Latitude"><input name="lng" value="<?=e((string)$lng)?>" placeholder="Longitude"><select name="radius"><option value="">Radius</option><?php foreach([1,5,10,25] as $r):?><option value="<?=$r?>" <?=((string)$radius===(string)$r)?'selected':''?>><?=$r?> km</option><?php endforeach;?></select><button class="btn">Apply</button></form><div class="grid"><?php foreach($items as $l):?><a class="card" href="/listing.php?id=<?=$l['id']?>"><?php if($l['image_path']):?><img class="product-img" src="<?=e($l['image_path'])?>" alt=""><?php else:?><div class="product-img placeholder">RADIUS</div><?php endif;?><div class="card-body"><span class="badge <?=e(trust_class($l['trust_status']??''))?>"><?=e(trust_label($l['trust_status']??''))?></span><h3><?=e($l['title'])?></h3><div class="price"><?=money($l['price'])?></div><div class="meta"><span><?=e($l['item_condition'])?></span><span><?=e($l['seller_name'])?></span><?php if($l['distance_km']!==null):?><span><?=number_format((float)$l['distance_km'],1)?> km away</span><?php endif;?></div></div></a><?php endforeach;?></div><?php if(!$items):?><div class="empty">No listings matched those filters.</div><?php endif;?><?php include __DIR__.'/includes/footer.php';?>