<?php
require_once __DIR__.'/includes/functions.php';
$q=trim($_GET['q']??'');$cat=trim($_GET['category']??'');$cond=trim($_GET['condition']??'');$trust=trim($_GET['trust']??'');$min=$_GET['min_price']??'';$max=$_GET['max_price']??'';$radius=$_GET['radius']??'';$lat=$_GET['lat']??'';$lng=$_GET['lng']??'';$sort=$_GET['sort']??'newest';
$where=["l.status='approved'"];$params=[];
if($q!==''){$where[]='(l.title LIKE :q1 OR l.description LIKE :q2 OR l.brand LIKE :q3)';$params[':q1']=$params[':q2']=$params[':q3']='%'.$q.'%';}
if($cat!==''){$where[]='l.category=:cat';$params[':cat']=$cat;}if($cond!==''){$where[]='l.item_condition=:cond';$params[':cond']=$cond;}if($trust!==''){$where[]='l.trust_status=:trust';$params[':trust']=$trust;}if($min!==''){$where[]='l.price>=:min';$params[':min']=(float)$min;}if($max!==''){$where[]='l.price<=:max';$params[':max']=(float)$max;}
$distance='NULL';$having='';if($lat!==''&&$lng!==''&&$radius!==''){$distance=haversine_sql();$params[':ulat1']=(float)$lat;$params[':ulat2']=(float)$lat;$params[':ulng']=(float)$lng;$having=' HAVING distance_km <= :radius';$params[':radius']=(float)$radius;}
$order=match($sort){'price_asc'=>'l.price ASC','price_desc'=>'l.price DESC','distance'=>($distance==='NULL'?'l.created_at DESC':'distance_km ASC'),'newest'=>'l.created_at DESC',default=>'l.created_at DESC'};
$sql="SELECT l.*,u.name seller_name,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path,$distance distance_km FROM listings l JOIN users u ON u.id=l.user_id WHERE ".implode(' AND ',$where).$having." ORDER BY $order LIMIT 100";$s=db()->prepare($sql);$s->execute($params);$items=$s->fetchAll();
$pageTitle='Browse nearby';include __DIR__.'/includes/header.php';?>
<div class="section-head" style="margin-top:16px"><div><div class="eyebrow">Nearby marketplace</div><h2>Browse listings</h2><p>Search local secondhand products with trust signals attached.</p></div></div>
<form class="hero-search" method="get" action="/listings.php" style="max-width:none"><span class="hero-search-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg></span><input name="q" value="<?=e($q)?>" placeholder="Search nearby phones, laptops, cameras..."><button class="hero-search-btn">Search</button></form>
<form class="filters">
<select name="category"><option value="">All categories</option><?php foreach(['phone','laptop','camera','furniture','bicycle','appliance','fashion','books','gaming','accessories'] as $v):?><option value="<?=$v?>" <?=$cat===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select>
<select name="condition"><option value="">Any condition</option><?php foreach(['new','excellent','good','fair','poor'] as $v):?><option value="<?=$v?>" <?=$cond===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select>
<input type="number" name="min_price" value="<?=e((string)$min)?>" placeholder="Min ৳"><input type="number" name="max_price" value="<?=e((string)$max)?>" placeholder="Max ৳">
<select name="trust"><option value="">Any trust status</option><?php foreach(['safe','low_risk','suspicious','high_risk'] as $v):?><option value="<?=$v?>" <?=$trust===$v?'selected':''?>><?=trust_label($v)?></option><?php endforeach;?></select>
<select name="sort"><option value="newest" <?=$sort==='newest'?'selected':''?>>Newest</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Price: Low → High</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Price: High → Low</option><option value="distance" <?=$sort==='distance'?'selected':''?>>Nearest</option></select>
<input name="lat" value="<?=e((string)$lat)?>" placeholder="Latitude"><input name="lng" value="<?=e((string)$lng)?>" placeholder="Longitude"><select name="radius"><option value="">Any radius</option><?php foreach([1,5,10,25] as $r):?><option value="<?=$r?>" <?=((string)$radius===(string)$r)?'selected':''?>><?=$r?> km</option><?php endforeach;?></select><button class="btn btn-primary btn-sm">Apply</button></form>
<?php if($items):?><div class="listing-grid"><?php foreach($items as $l):?><a class="listing-card" href="/listing.php?id=<?=$l['id']?>"><div class="card-image-wrap"><img class="card-image" src="<?=e(listing_visual($l))?>" alt="<?=e($l['title'])?>"></div><div class="card-content"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:8px"><h3 class="card-title"><?=e($l['title'])?></h3><div class="card-price"><?=money($l['price'])?></div></div><p class="card-desc"><?=e($l['description'])?></p><div class="card-meta"><span class="meta-pill"><?=e($l['category'])?></span><span class="meta-pill"><?=e($l['item_condition'])?></span><?php if($l['distance_km']!==null):?><span><?=number_format((float)$l['distance_km'],1)?>km</span><?php endif;?><span class="badge <?=e(trust_class($l['trust_status']??''))?>"><?=e(trust_label($l['trust_status']??''))?></span></div></div></a><?php endforeach;?></div><?php else:?><div class="empty">No listings matched those filters.</div><?php endif;?>
<?php include __DIR__.'/includes/footer.php';?>