<?php
require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/functions.php';require_once __DIR__.'/includes/csrf.php';
$viewer=current_user();$profileId=isset($_GET['id'])&&ctype_digit((string)$_GET['id'])?(int)$_GET['id']:(int)($viewer['id']??0);if($profileId<=0)redirect('/login.php');$pdo=db();$q=$pdo->prepare('SELECT id,name,role,location,latitude,longitude,profile_image,is_active,created_at FROM users WHERE id=? LIMIT 1');$q->execute([$profileId]);$profileUser=$q->fetch();$isOwn=$viewer&&(int)$viewer['id']===$profileId;$isAdmin=$viewer&&($viewer['role']??'')==='admin';if(!$profileUser||(!(bool)$profileUser['is_active']&&!$isOwn&&!$isAdmin)){http_response_code(404);exit('Profile not found.');}
$q=$pdo->prepare("SELECT COUNT(*) FROM trade_requests WHERE (buyer_id=? OR seller_id=?) AND status='completed'");$q->execute([$profileId,$profileId]);$trades=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT COALESCE(AVG(rating),0) FROM reviews WHERE reviewed_user_id=?');$q->execute([$profileId]);$rating=(float)$q->fetchColumn();
if($isOwn||$isAdmin){$q=$pdo->prepare("SELECT l.*,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path FROM listings l WHERE l.user_id=? AND l.status<>'removed' ORDER BY l.created_at DESC");}else{$q=$pdo->prepare("SELECT l.*,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path FROM listings l WHERE l.user_id=? AND l.status='approved' AND l.availability_status IN ('available','reserved') ORDER BY l.created_at DESC");}$q->execute([$profileId]);$own=$q->fetchAll();$activeCount=count(array_filter($own,fn($x)=>in_array($x['availability_status']??'available',['available','reserved'],true)&&($x['status']??'')==='approved'));
$r=$pdo->prepare('SELECT r.*,u.name reviewer FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.reviewed_user_id=? ORDER BY r.created_at DESC');$r->execute([$profileId]);$reviews=$r->fetchAll();$pageTitle=$profileUser['name'].' · Profile';include __DIR__.'/includes/header.php';?>
<div class="section-head"><div><h2><?=e($profileUser['name'])?></h2><p><?=e($profileUser['location']?:'Location not set')?> · Member since <?=date('M Y',strtotime($profileUser['created_at']))?><?php if(!$profileUser['is_active']):?> · Disabled account<?php endif;?></p></div><?php if(!$isOwn&&$viewer&&$profileUser['is_active']):?><a class="btn btn-primary btn-sm" href="/messages.php">Message from a listing</a><?php endif;?></div>
<div class="stats"><div class="stat"><span class="muted">Rating</span><strong><?=number_format($rating,1)?></strong></div><div class="stat"><span class="muted">Completed trades</span><strong><?=$trades?></strong></div><div class="stat"><span class="muted">Active listings</span><strong><?=$activeCount?></strong></div><div class="stat"><span class="muted">Reviews</span><strong><?=count($reviews)?></strong></div></div>
<div class="section-head"><div><h2><?=$isOwn?'Your listings':'Listings'?></h2><p><?=$isOwn||$isAdmin?'Private/moderation states are visible to you.':'Only approved seller inventory is shown.'?></p></div><?php if($isOwn):?><a class="btn btn-sm" href="/create-listing.php">Sell item</a><?php endif;?></div>
<?php if($own):?><div class="grid"><?php foreach($own as $l):?><div class="card"><a href="/listing.php?id=<?=$l['id']?>"><img class="product-img" loading="lazy" src="<?=e(listing_visual($l))?>" alt="<?=e($l['title'])?>"><div class="card-body"><span class="badge <?=e(trust_class((string)($l['trust_status']??''),(string)$l['status']))?>"><?=e(trust_label((string)($l['trust_status']??''),(string)$l['status']))?></span><h3><?=e($l['title'])?></h3><strong><?=money($l['price'])?></strong><div class="meta"><span><?=e(availability_label((string)($l['availability_status']??'available')))?></span><?php if($isOwn||$isAdmin):?><span>Moderation: <?=e($l['status'])?></span><?php endif;?></div></div></a><?php if($isOwn&&($l['availability_status']??'available')!=='sold'&&$l['status']!=='removed'):?><div class="profile-card-actions"><a class="btn btn-sm" href="/edit-listing.php?id=<?=$l['id']?>">Edit</a><form method="post" action="/delete-listing.php" data-confirm="Withdraw this listing? Existing fraud and trade history will be preserved."><?=csrf_field()?><input type="hidden" name="id" value="<?=$l['id']?>"><button class="btn btn-sm btn-danger">Withdraw</button></form></div><?php endif;?></div><?php endforeach;?></div><?php else:?><div class="empty">No listings to show.</div><?php endif;?>
<div class="section-head"><h2>Reviews</h2></div><?php foreach($reviews as $rv):?><div class="card card-body" style="margin-bottom:10px"><strong><?=e($rv['reviewer'])?> · <?=$rv['rating']?>/5</strong><p><?=e($rv['comment'])?></p></div><?php endforeach;?><?php if(!$reviews):?><div class="empty">No reviews yet.</div><?php endif;?><?php include __DIR__.'/includes/footer.php';?>
