<?php
require_once __DIR__.'/includes/functions.php';
$distanceSql="(6371 * ACOS(LEAST(1, COS(RADIANS(23.7465)) * COS(RADIANS(l.latitude)) * COS(RADIANS(l.longitude)-RADIANS(90.376)) + SIN(RADIANS(23.7465)) * SIN(RADIANS(l.latitude)))))";
$items=db()->query("SELECT l.*,(SELECT image_path FROM listing_images WHERE listing_id=l.id ORDER BY id LIMIT 1) image_path,$distanceSql distance_km FROM listings l WHERE l.status='approved' ORDER BY distance_km ASC,l.created_at DESC LIMIT 16")->fetchAll();
$pageTitle='Trust Radar';include __DIR__.'/includes/header.php';
?>
<section class="trust-hero" style="grid-template-columns:minmax(0,.72fr) minmax(480px,1.28fr)">
<div class="trust-hero-copy"><div class="eyebrow">Live nearby scan</div><h1>Trust Radar</h1><p>Explore nearby listings spatially. Teal nodes are verified, amber nodes deserve a closer look, and red nodes carry stronger risk signals. The AI score supports review; it does not prove fraud.</p><div class="trust-radar-stats"><span><strong><?=count($items)?></strong> visible listings</span><span><strong><?=count(array_filter($items,fn($x)=>($x['trust_status']??'')==='safe'))?></strong> verified</span><span><strong><?=count(array_filter($items,fn($x)=>($x['trust_status']??'')!=='safe'))?></strong> review signals</span></div><div class="hero-actions" style="margin-top:22px"><a class="btn btn-primary" href="/listings.php">Browse Listings</a><a class="btn btn-secondary" href="/create-listing.php">Sell an Item</a></div></div>
<div class="trust-radar-shell" data-radar><div class="trust-radar-panel"><div class="trust-radar-depth trust-radar-depth-a"></div><div class="trust-radar-depth trust-radar-depth-b"></div><div class="trust-radar-sweep"></div><div class="trust-radar-ring trust-radar-ring-1"><span>500m</span></div><div class="trust-radar-ring trust-radar-ring-2"><span>2km</span></div><div class="trust-radar-ring trust-radar-ring-3"><span>5km</span></div><div class="trust-radar-center"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 11 12 4l9 7"/><path d="M5 10v10h14V10"/></svg></div>
<?php $radar=array_slice($items,0,8);$n=max(count($radar),1);foreach($radar as $i=>$l):$angle=($i/$n)*M_PI*2-M_PI/2;$distance=(float)($l['distance_km']??2);$radius=20+min($distance/5,1)*30;$x=50+$radius*cos($angle);$y=50+$radius*sin($angle);$state=trust_state($l['trust_status']??'');?>
<button type="button" class="trust-radar-node <?=$state?><?=$i===0?' selected':''?>" style="left:<?=number_format($x,2,'.','')?>%;top:<?=number_format($y,2,'.','')?>%" data-radar-node data-title="<?=e($l['title'])?>" data-price="<?=e(money($l['price']))?>" data-distance="<?=number_format($distance,1)?> km" data-state="<?=$state?>" data-trust="<?=e(trust_label($l['trust_status']??''))?> · risk <?=round((float)$l['fraud_score'])?>/100" data-image="<?=e(listing_visual($l))?>" data-href="/listing.php?id=<?=$l['id']?>"><img src="<?=e(listing_visual($l))?>" alt=""><span class="trust-radar-node-distance"><?=number_format($distance,1)?>km</span></button><?php endforeach;?>
<?php if($radar):$f=$radar[0];?><div class="trust-radar-card <?=trust_state($f['trust_status']??'')?>" data-radar-card><img src="<?=e(listing_visual($f))?>" alt="" data-radar-card-image><div class="trust-radar-card-body"><strong data-radar-card-title><?=e($f['title'])?></strong><span class="trust-radar-price" data-radar-card-price><?=money($f['price'])?></span><span data-radar-card-distance><?=number_format((float)$f['distance_km'],1)?> km away</span><span data-radar-card-trust><?=e(trust_label($f['trust_status']??''))?> · risk <?=round((float)$f['fraud_score'])?>/100</span><a class="btn btn-primary btn-sm" data-radar-card-link href="/listing.php?id=<?=$f['id']?>">View Listing</a></div></div><?php endif;?></div></div>
</section>
<div class="section-head"><div><h2>Listings detected</h2><p>The same radar data as accessible cards.</p></div></div><div class="listing-grid"><?php foreach($items as $l):?><a class="listing-card" href="/listing.php?id=<?=$l['id']?>"><div class="card-image-wrap"><img class="card-image" src="<?=e(listing_visual($l))?>" alt="<?=e($l['title'])?>"></div><div class="card-content"><h3 class="card-title"><?=e($l['title'])?></h3><div class="card-price"><?=money($l['price'])?></div><div class="card-meta"><span><?=number_format((float)$l['distance_km'],1)?>km away</span><span class="badge <?=e(trust_class($l['trust_status']??''))?>"><?=e(trust_label($l['trust_status']??''))?> · <?=round((float)$l['fraud_score'])?></span></div></div></a><?php endforeach;?></div>
<?php include __DIR__.'/includes/footer.php';?>